name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true

  - type: dropdown
    id: OS
    attributes:
      label: Which OS are you using?
      multiple: false
      options:
        - Window
        - Linux

  - type: textarea
    id: To Reproduce
    attributes:
      label: To Reproduce
      description: Describe the step how bug can be obeserve.
      value: "0. Open software /n 1. Do something.. /n"
    validations:
      required: true

  - type: textarea
    id: Expected Behavior
    attributes:
      label: Expected Behavior
      description: What is the behavior should expected?
    validations:
      required: true

  - type: textarea
    id: Actual Behavior
    attributes:
      label: Actual Behavior
      description: Explain about current behavior. If there is screenshot it will be even better. 
    validations:
      required: true

  - type: input
    id: Related files
    attributes:
      label: Related files
      description: Which files of this repostiory is related with this issue?
    validations:
      required: false

